### PR TITLE
Fix xr_linregress problem with dask

### PR DESCRIPTION
**Pull request by jbusecke**
I recently encountered a problem when using my trused `xr_linregress`. This PR establishes tests to isolate the reason.

### CODE REVIEW

**Comment by jbusecke** [comment]
It turns out that this problem was related to upstream changes in [dask](https://github.com/pydata/xarray/issues/3574). Until this is fixed upstream, I downgraded test versions to `dask < 2.0` and added a warning. This addresses #16.

**Comment by AndrewWilliams3142** [comment]
Hi, 

I'm keen on using this functionality of xarrayutils, however I'd prefer not to have to downgrade my `dask` if possible. Is anyone aware of a workaround for this multiple outputs issue? Perhaps via stacking the outputs into a single dimension?

Cheers!

**Comment by jbusecke** [comment]
If you run xarray 0.15 this works out of the box. If not please let me know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment]
I might want to remove the warning now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment]
Also thanks for using xarrayutils!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndrewWilliams3142** [comment]
> If you run xarray 0.15 this works out of the box. If not please let me know
> 
> Sent with [GitHawk](http://githawk.com)

Beautiful! It works now. Do you know what changed to fix this? Initially there was an issue with `ValueError: cannot call `vectorize` with a signature including new output dimensions on size 0 inputs`. Raised in this [Github issue](https://github.com/pydata/xarray/issues/3574).

Thanks again, great package ! :))

**Comment by jbusecke** [comment]
[This](https://github.com/pydata/xarray/pull/3660) was the required fix. As far as I understand when using 'vectorize' dask needed to recieve some metadata of the array shape to prevent it from 'testing' with a 0D input...

**Pull request merged**
